In [1]:
import pandas as pd
import csv
import json

In [8]:
df = pd.read_json('../mental_states/races_2023.json', orient='records')

In [12]:
df

,Wyoming,Wisconsin,West Virginia,Washington,Virginia,Vermont,Utah,Texas,Tennessee,South Dakota,...,District of Columbia,Delaware,Connecticut,Colorado,California,Arkansas,Arizona,Alaska,Alabama,mean
0,"{'state': 'Wyoming', 'value': 90.5647949942367...","{'state': 'Wisconsin', 'value': 85.68164508758...","{'state': 'West Virginia', 'value': 388.601036...","{'state': 'Washington', 'value': 111.761019427...","{'state': 'Virginia', 'value': 108.03802938634...","{'state': 'Vermont', 'value': 432.276657060518...","{'state': 'Utah', 'value': 106.40355968272394,...","{'state': 'Texas', 'value': 118.586041907276, ...","{'state': 'Tennessee', 'value': 171.3623305276...","{'state': 'South Dakota', 'value': 65.52185426...",...,"{'state': 'District of Columbia', 'value': 171...","{'state': 'Delaware', 'value': 329.70656116056...","{'state': 'Connecticut', 'value': 184.93404019...","{'state': 'Colorado', 'value': 182.81044170228...","{'state': 'California', 'value': 112.519504416...","{'state': 'Arkansas', 'value': 163.15943605405...","{'state': 'Arizona', 'value': 46.2150252570486...","{'state': 'Alaska', 'value': 40.35253441429214...","{'state': 'Alabama', 'value': 223.681874667140...","{'value': 171.17477969438107, 'races': 'Americ..."
1,"{'state': 'Wyoming', 'value': 97.0245795601552...","{'state': 'Wisconsin', 'value': 30.73207026321...","{'state': 'West Virginia', 'value': 57.0993528...","{'state': 'Washington', 'value': 37.9941078393...","{'state': 'Virginia', 'value': 31.895019820476...","{'state': 'Vermont', 'value': 43.7550010915816...","{'state': 'Utah', 'value': 35.08273678759074, ...","{'state': 'Texas', 'value': 33.70369528829914,...","{'state': 'Tennessee', 'value': 34.32518825220...","{'state': 'South Dakota', 'value': 65.11264487...",...,"{'state': 'District of Columbia', 'value': 37....","{'state': 'Delaware', 'value': 47.667850418285...","{'state': 'Connecticut', 'value': 39.652842159...","{'state': 'Colorado', 'value': 55.190042554427...","{'state': 'California', 'value': 30.6530118172...","{'state': 'Arkansas', 'value': 57.592030508210...","{'state': 'Arizona', 'value': 54.6870092487556...","{'state': 'Alaska', 'value': 96.19844364660814...","{'state': 'Alabama', 'value': 80.1771533292608...","{'value': 43.7550010915817, 'races': 'Asian/Pa..."
2,"{'state': 'Wyoming', 'value': 31.2023623492447...","{'state': 'Wisconsin', 'value': 25.90790005895...","{'state': 'West Virginia', 'value': 24.9754148...","{'state': 'Washington', 'value': 30.6257439372...","{'state': 'Virginia', 'value': 23.526232352309...","{'state': 'Vermont', 'value': 31.2023623492447...","{'state': 'Utah', 'value': 55.433769244336936,...","{'state': 'Texas', 'value': 24.348304143370747...","{'state': 'Tennessee', 'value': 21.92940802685...","{'state': 'South Dakota', 'value': 38.11883546...",...,"{'state': 'District of Columbia', 'value': 19....","{'state': 'Delaware', 'value': 28.133163641235...","{'state': 'Connecticut', 'value': 29.244576045...","{'state': 'Colorado', 'value': 37.826410399741...","{'state': 'California', 'value': 27.9074925708...","{'state': 'Arkansas', 'value': 22.092242620011...","{'state': 'Arizona', 'value': 36.2378617893843...","{'state': 'Alaska', 'value': 50.67353574595668...","{'state': 'Alabama', 'value': 18.2611220711106...","{'value': 31.20236234924473, 'races': 'Black/A..."
3,"{'state': 'Wyoming', 'value': 24.5551426653788...","{'state': 'Wisconsin', 'value': 35.70484297778...","{'state': 'West Virginia', 'value': 35.6252226...","{'state': 'Washington', 'value': 25.4919955134...","{'state': 'Virginia', 'value': 26.745179634678...","{'state': 'Vermont', 'value': 34.7608453837597...","{'state': 'Utah', 'value': 32.007390060692494,...","{'state': 'Texas', 'value': 24.28862783674095,...","{'state': 'Tennessee', 'value': 25.83135879992...","{'state': 'South Dakota', 'value': 29.06413485...",...,"{'state': 'District of Columbia', 'value': 33....","{'state': 'Delaware', 'value': 33.592522699653...","{'state': 'Connecticut', 'value': 28.252489358...","{'state': 'Colorado', 'value': 28.688214015623...","{'state': 'California', 'value': 22.5013575395...","{'state': 'Arkansas', 'value': 29.847538771952...","{'state': 'Arizona', 'value': 27.4762432574745...","{'state': 'Alaska', 'value': 38.36877877658408...","{'state': 'Alabama', 'value': 32.3425993498308...","{'value': 27.61562964885499, 'races': 'Hispani..."
4,"{'state': 'Wyoming', 'value': 99.5475113122172...","{'state': 'Wisconsin', 'value': 78.26150262085...","{'state': 'West Virginia', 'value': 77.5679465...","{'state': 'Washington', 'value': 60.4326628324...","{'state': 'Virginia', 'value': 103.67859635131...","{'state': 'Vermont', 'value': 89.3147125690159...","{'state': 'Utah', 'value': 76.28266673681165, ...","{'state': 'Texas', 'value': 118.91008243446744...","{'state': 'Tennessee', 'value': 81.92875177822...","{'state': 'South Dakota', 'value': 91.31542269...",...,"{'state': 'District of Columbia', 'value': 78....","{'state': 'Delaware', 'value': 91.295201047910...","{'state': 'Connecticut', 'value': 92.623902847...","{'state': 'Colorado', 'value': 120.70592152727...","{'state': 'California', 'value': 80.4790468273...","{'state': 'Arkansas', 'value': 95.994964198599...","{'state': 'Arizona', 'value': 104.655005691763...","{'state': 'Alaska', 'value': 59.31652060770732...","{'state': 'Alabama', 'value': 75.5199256419193...","{'value': 81.82491701081483, 'races': 'Multira..."
5,"{'state': 'Wyoming', 'value': 90.5647949942367...","{'state': 'Wisconsin', 'value': 116.1462300076...","{'state': 'West Virginia', 'value': 336.787564...","{'state': 'Washington', 'value': 127.428452057...","{'state': 'Virginia', 'value': 164.21780466724...","{'state': 'Vermont', 'value': 480.307396733909...","{'state': 'Utah', 'value': 116.07661056297157,...","{'state': 'Texas', 'value': 145.39679920805148...","{'state': 'Tennessee', 'value': 211.6828788871...","{'state': 'South Dakota', 'value': 76.44216331...",...,"{'state': 'District of Columbia', 'value': 199...","{'state': 'Delaware', 'value': 362.67721727662...","{'state': 'Connecticut', 'value': 221.92084823...","{'state': 'Colorado', 'value': 217.75949673360...","{'state': 'California', 'value': 131.169146032...","{'state': 'Arkansas', 'value': 171.52658662092...","{'state': 'Arizona', 'value': 55.5296815104073...","{'state': 'Alaska', 'value': 50.44066801786517...","{'state': 'Alabama', 'value': 244.984910349724...","{'value': 199.50609870868158, 'races': 'Americ..."
6,"{'state': 'Wyoming', 'value': 54.0827503748804...","{'state': 'Wisconsin', 'value': 41.51525281171...","{'state': 'West Virginia', 'value': 95.1655881...","{'state': 'Washington', 'value': 44.2649800069...","{'state': 'Virginia', 'value': 42.635179555943...","{'state': 'Vermont', 'value': 54.0827503748804...","{'state': 'Utah', 'value': 46.77698238345431, ...","{'state': 'Texas', 'value': 41.46690600077253,...","{'state': 'Tennessee', 'value': 41.47626913808...","{'state': 'South Dakota', 'value': 78.13517385...",...,"{'state': 'District of Columbia', 'value': 47....","{'state': 'Delaware', 'value': 59.584813022856...","{'state': 'Connecticut', 'value': 53.056619790...","{'state': 'Colorado', 'value': 72.618477045299...","{'state': 'California', 'value': 38.8825551281...","{'state': 'Arkansas', 'value': 70.044361428904...","{'state': 'Arizona', 'value': 69.0977751994413...","{'state': 'Alaska', 'value': 111.6589078040987...","{'state': 'Alabama', 'value': 95.4489920586438...","{'value': 54.08275037488041, 'races': 'Asian/P..."
7,"{'state': 'Wyoming', 'value': 39.4229594495791...","{'state': 'Wisconsin', 'value': 31.19522660159...","{'state': 'West Virginia', 'value': 31.2192685...","{'state': 'Washington', 'value': 30.6257439372...","{'state': 'Virginia', 'value': 28.171155150073...","{'state': 'Vermont', 'value': 57.5705238917674...","{'state': 'Utah', 'value': 75.59150351500492, ...","{'state': 'Texas', 'value': 29.08575698574605,...","{'state': 'Tennessee', 'value': 23.13811555589...","{'state': 'South Dakota', 'value': 47.64854433...",...,"{'state': 'District of Columbia', 'value': 23....","{'state': 'Delaware', 'value': 33.045303324625...","{'state': 'Connecticut', 'value': 31.855698906...","{'state': 'Colorado', 'value': 49.174333519663...","{'state': 'California', 'value': 32.9526581659...","{'state': 'Arkansas', 'value': 22.521218204865...","{'state': 'Arizona', 'value': 48.0225322899971...","{'state': 'Alaska', 'value': 80.2330982644314,...","{'state': 'Alabama', 'value': 20.9553859832416...","{'value': 39.422959449579146, 'races': 'Black/..."
8,"{'state': 'Wyoming', 'value': 22.9181331543536...","{'state': 'Wisconsin', 'value': 37.28670310971...","{'state': 'West Virginia', 'value': 32.6564541...","{'state': 'Washington', 'value': 27.6635358719...","{'state': 'Virginia', 'value': 30.031663572838...","{'state': 'Vermont', 'value': 55.6173526140155...","{'state': 'Utah', 'value': 36.66669367712242, ...","{'state': 'Texas', 'value': 27.22350370034715,...","{'state': 'Tennessee', 'value': 28.88415574900...","{'state': 'South Dakota', 'value': 36.33016857...",...,"{'state': 'District of Columbia', 'value': 42....","{'state': 'Delaware', 'value': 40.508630314287...","{'state': 'Connecticut', 'value': 30.135988648...","{'state': 'Colorado', 'value': 30.002768296662...","{'state': 'California', 'value': 25.0339503910...","{'state': 'Arkansas', 'value': 34.225177791839...","{'state': 'Arizona', 'value': 29.1350257451548...","{'state': 'Alaska', 'value': 38.36877877658408...","{'state': 'Alabama', 'value': 37.3183838651894...","{'value': 31.702190249213732, 'races': 'Hispan..."
9,"{'state': 'Wyoming', 'value': 90.4977375565610...","{'state': 'Wisconsin', 'value': 84.63162492719...","{'state': 'West Virginia', 'value': 74.5845639...","{'state': 'Washington', 'value': 65.6876769917...","{'state': 'Virginia', 'value': 117.23656664340...","{'state': 'Vermont', 'value': 89.3147125690159...","{'state': 'Utah', 'value': 99.95659779306354, ...","{'state': 'Texas', 'value': 134.53947159992143...","{'state': 'Tennessee', 'value': 87.88720645300...","{'state': 'South Dakota', 'value': 67.28504830...",...,"{'state': 'District of Columbia', 'value': 84....","{'state': 'Delaware', 'value': 127.01941015361...","{'state': 'Connecticut', 'value': 105.85588896...","{'state': 'Colorado', 'value': 124.86819468338...","{'state': 'California', 'value': 96.2843798030...","{'state': 'Arkansas', 'value': 100.71602801164...","{'state': 'Arizona', 'value': 115.671322080370...","{'state': 'Alaska', 'value': 68.88370135088591...","{'state': 'Alabama', 'value': 97.5949808295573...","{'value': 90.28906612880283, 'races': 'Multira..."
10,"{'state': 'Wyoming', 'value': 69.5317379385828...","{'state': 'Wisconsin', 'value': 57.12109672505...","{'state': 'West Virginia', 'value': 129.533678...","{'state': 'Washington', 'value': 34.4683517860...","{'state': 'Virginia', 'value': 43.215211754537...","{'state': 'Vermont', 'value': 69.5317379385828...","{'state': 'Utah', 'value': 29.01915264074289, ...","{'state': 'Texas', 'value': 57.74624649397789,...","{'state': 'Tennessee', 'value': 80.64109671891...","{'state': 'South Dakota', 'value': 24.57069535...",...,"{'state': 'District of Columbia', 'value': 69....","{'state': 'Delaware', 'value': 69.531737938582...","{'state': 'Connecticut', 'value': 98.631488102...","{'state': 'Colorado', 'value': 64.521332365513...","{'state': 'California', 'value': 48.4890682017...","{'state': 'Arkansas', 'value': 62.753629251558...","{'state': 'Arizona', 'value': 13.9719843800379...","{'state': 'Alaska', 'value': 25.67888553636772...","{'state': 'Alabama', 'value': 74.5606248890467...","{'value': 69.53173793858286, 'races': 'America..."
11,"{'state': 'Wyoming', 'value': 80.8538163001293...","{'state': 'Wisconsin', 'value': 8.626546038797...","{'state': 'West Virginia', 'value': 15.3642125...","{'state': 'Washington', 'value': 9.22187083478...","{'state': 'Virginia', 'value': 5.8582689466181...","{'state': 'Vermont', 'value': 15.3642125692043...","{'state': 'Utah', 'value': 10.85894233901618, ...","{'state': 'Texas', 'value': 7.258286438491387,...","{'state': 'Tennessee', 'value': 7.866188974463...","{'state': 'South Dakota', 'value': 15.36421256...",...,"{'state': 'District of Columbia', 'value': 27....","{'state': 'Delaware', 'value': 16.683747646399...","{'state': 'Connecticut', 'value': 17.871703508...","{'state': 'Colorado', 'value': 16.944311310569...","{'state': 'California', 'value': 7.78954792592...","{'state': 'Arkansas', 'value': 15.565413650867...","{'state': 'Arizona', 'value': 15.5192864084306...","{'state': 'Alaska', 'value': 34.35658701664577...","{'state': 'Alabama', 'value': 34.3616371411117...","{'value': 15.364212569204387, 'races': 'Asian/..."
12,"{'state': 'Wyoming', 'value': 14.1496135164979...","{'state': 'Wisconsin', 'value': 13.74704901087...","{'state': 'West Virginia', 'value': 15.6096342...","{'state': 'Washington', 'value': 17.0493832227...","{'state': 'Virginia', 'value': 9.2898455955273...","{'state': 'Vermont', 'value': 14.1496135164979...","{'state': 'Utah', 'value': 22.677451054501475,...","{'state': 'Texas', 'value': 9.943142302892351,...","{'state': 'Tennessee', 'value': 10.36035024890...","{'state': 'South Dakota', 'value': 14.14961351...",...,"{'state': 'District of Columbia', 'value': 10....","{'state': 'Delaware', 'value': 11.610511978922...","{'state': 'Connecticut', 'value': 9.6611545863...","{'state': 'Colorado', 'value': 18.492911750984...","{'state': 'California', 'value': 12.5901880165...","{'state': 'Arkansas', 'value': 6.8636093576734...","{'state': 'Arizona', 'value': 15.0254548882813...","{'state': 'Alaska', 'value': 46.45074110046029...","{'state': 'Alabama', 'value': 7.18470376568286...","{'value': 14.149613516497999, 'races': 'Black/..."
13,"{'state': 'Wyoming', 'value': 11.4590665771768...","{'state': 'Wisconsin', 'value': 13.33282111195...","{'state': 'West Virginia', 'value': 13.5643692...","{'state': 'Washington', 'value': 12.0850941693...","{'state': 'Virginia', 'value': 12.352646526186...","{'state': 'Vermont', 'value': 34.7608453837597...","{'state': 'Utah', 'value': 13.167597176867163,...","{'state': 'Texas', 'value': 10.2973661766183, ...","{'state': 'Tennessee', 'value': 16.90779848722...","{'state': 'South Dakota', 'value': 21.79810114...",...,"{'state': 'District of Columbia', 'value': 10....","{'state': 'Delaware', 'value': 16.796261349826...","{'state': 'Connecticut', 'value': 9.4174964527...","{'state': 'Colorado', 'value': 13.918810034534...","{'state': 'California', 'value': 8.79742779968...","{'state': 'Arkansas', 'value': 13.928851426911...","{'state': 'Arizona', 'value': 11.3137472236659...","{'state': 'Alaska', 'value': 20.09793174011547...","{'state': 'Alabama', 'value': 12.0248125787832...","{'value': 13.564369255731801, 'races': 'Hispan..."
14,"{'state': 'Wyoming', 'value': 49.5869111289520...","{'state': 'Wisconsin', 'value': 62.79120559114...","{'state': 'West Virginia', 'value': 29.8338255...","{'state': 'Washington', 'value': 37.3689895775...","{'state': 'Virginia', 'value': 51.839298175655...","{'state': 'Vermont', 'value': 48.7171159467359...","{'state': 'Utah', 'value': 60.50004603264372, ...","{'state': 'Texas', 'value': 66.31929997233175,...","{'state': 'Tennessee', 'value': 52.13647840432...","{'state': 'South Dakota', 'value': 52.86682366...",...,"{'state': 'District of Columbia', 'value': 54....","{'state': 'Delaware', 'value': 51.601635374905...","{'state': 'Connecticut', 'value': 52.927944484...","{'state': 'Colorado', 'value': 74.920916810033...","{'state': 'California', 'value': 41.9482080596...","{'state': 'Arkansas', 'value': 59.800141631914...","{'state': 'Arizona', 'value': 72.2180741030882...","{'state': 'Alaska', 'value': 15.30748918908576...","{'state': 'Alabama', 'value': 63.9014755431625...","{'value': 49.58691112895207, 'races': 'Multira..."
15,"{'state': 'Wyoming', 'value': 56.6173393506867...","{'state': 'Wisconsin', 'value': 34.27265803503...","{'state': 'West Virginia', 'value': 207.253886...","{'state': 'Washington', 'value': 45.9578023814...","{'state': 'Virginia', 'value': 82.108902333621...","{'state': 'Vermont', 'value': 56.6173393506867...","{'state': 'Utah', 'value': 19.34610176049526, ...","{'state': 'Texas', 'value': 41.24731892426992,...","{'state': 'Tennessee', 'value': 95.76130235371...","{'state': 'South Dakota', 'value': 36.85604302...",...,"{'state': 'District of Columbia', 'value': 56....","{'state': 'Delaware', 'value': 56.617339350686...","{'state': 'Connecticut', 'value': 56.617339350...","{'state': 'Colorado', 'value': 56.456165819824...","{'state': 'California', 'value': 43.5158304374...","{'state': 'Arkansas', 'value': 50.202903401246...","{'state': 'Arizona', 'value': 14.3302403897825...","{'state': 'Alaska', 'value': 22.01047331688661...","{'state': 'Alabama', 'value': 49.7070832593644...","{'value': 56.61733935068671, 'races': 'America..."
16,"{'state': 'Wyoming', 'value': 9.76992462538224...","{'state': 'Wisconsin', 'value': 7.009068656523...","{'state': 'West Virginia', 'value': 9.76992462...","{'state': 'Washington', 'value': 9.46778739038...","{'state': 'Virginia', 'value': 6.6719174114262...","{'state': 'Vermont', 'value': 9.76992462538224...","{'state': 'Utah', 'value': 12.529548852710976,...","{'state': 'Texas', 'value': 6.816477698757129,...","{'state': 'Tennessee', 'value': 5.720864708700...","{'state': 'South Dakota', 'value': 9.769924625...",...,"{'state': 'District of Columbia', 'value': 27....","{'state': 'Delaware', 'value': 16.683747646399...","{'state': 'Connecticut', 'value': 6.1433980810...","{'state': 'Colorado', 'value': 10.650709966643...","{'state': 'California', 'value': 5.81771675639...","{'state': 'Arkansas', 'value': 14.008872285780...","{'state': 'Arizona', 'value': 12.9327386736922...","{'state': 'Alaska', 'value': 15.46046415749059...","{'state': 'Alabama', 'value': 13.9991855019344...","{'value': 9.769924625382247, 'races': 'Asian/P..."
17,"{'state': 'Wyoming', 'value': 10.2354492896474...","{'state': 'Wisconsin', 'value': 8.459722468229...","{'state': 'West Virginia', 'value': 7.80481713...","{'state': 'Washington', 'value': 11.6819848007...","{'state': 'Virginia', 'value': 8.4453141777521...","{'state': 'Vermont', 'value': 10.2354492896474...","{'state': 'Utah', 'value': 15.118300703000983,...","{'state': 'Texas', 'value': 7.684589203620406,...","{'state': 'Tennessee', 'value': 7.079572670086...","{'state': 'South Dakota', 'value': 10.23544928...",...,"{'state': 'District of Columbia', 'value': 8.4...","{'state': 'Delaware', 'value': 8.9311630607095...","{'state': 'Connecticut', 'value': 10.444491444...","{'state': 'Colorado', 'value': 19.753792097642...","{'state': 'California', 'value': 9.36310011335...","{'state': 'Arkansas', 'value': 8.3650239046644...","{'state': 'Arizona', 'value': 12.9631375506740...","{'state': 'Alaska', 'value': 33.78235716397111...","{'state': 'Alabama', 'value': 5.31368716003628...","{'value': 10.235449289647399, 'races': 'Black/..."

In [2]:
df = pd.read_csv('../mental_trend/line_chart.csv')

In [3]:
df['Week'] = pd.to_datetime(df['Week'])

In [4]:
# group df by month
df = df.groupby(pd.Grouper(key='Week', freq='M')).mean().reset_index()

In [5]:
df['month'] = df['Week'].dt.strftime('%Y-%m')

In [7]:
df.iloc[:, 1:]

,anxiety,panic,depression,stress,trauma,mental health,medication,therapist,counseling,meditation,month
0,77.00,29.00,78.00,54.00,15.00,41.00,63.00,36.00,42.00,24.00,2018-10
1,80.75,28.25,75.25,52.75,14.50,38.25,58.00,31.00,39.00,23.50,2018-11
2,77.60,30.00,70.60,47.00,13.00,32.80,58.40,30.00,33.20,24.00,2018-12
3,82.50,34.00,74.50,48.75,14.00,38.25,63.00,37.00,42.75,26.25,2019-01
4,82.75,29.50,79.75,54.00,14.75,40.25,63.75,35.25,43.00,26.25,2019-02
...,...,...,...,...,...,...,...,...,...,...,...
56,78.50,17.75,47.75,47.00,24.75,53.75,86.75,44.50,39.50,20.75,2023-06
57,78.40,18.00,45.20,45.80,24.60,48.80,82.20,44.40,40.40,19.40,2023-07
58,83.00,18.25,47.00,47.00,26.25,50.00,82.50,46.50,43.50,20.25,2023-08
59,82.25,19.25,55.25,57.00,26.00,59.50,85.75,46.50,43.50,20.75,2023-09
60,82.50,20.50,57.75,56.75,27.25,64.00,85.25,45.25,43.25,19.50,2023-10

In [62]:
df.iloc[0:2, 1:].to_clipboard()

In [58]:
df.iloc[:, 1:].to_json('../home/trend_data.json', orient='records')

In [8]:
melted_df = pd.melt(df.iloc[:, 1:], id_vars=['month'], var_name='keywords')
melted_df

       month    keywords  value
0    2018-10     anxiety  77.00
1    2018-11     anxiety  80.75
2    2018-12     anxiety  77.60
3    2019-01     anxiety  82.50
4    2019-02     anxiety  82.75
..       ...         ...    ...
605  2023-06  meditation  20.75
606  2023-07  meditation  19.40
607  2023-08  meditation  20.25
608  2023-09  meditation  20.75
609  2023-10  meditation  19.50

[610 rows x 3 columns]

In [44]:
melted_df = pd.melt(df.iloc[:, 1:], id_vars='month', var_name='keyword', value_name='value')

In [46]:
melted_df

       month  keyword  value
0    2018-11  anxiety  88.00
1    2018-12  anxiety  78.60
2    2019-01  anxiety  82.25
3    2019-02  anxiety  80.75
4    2019-03  anxiety  84.80
..       ...      ...    ...
605  2023-07   stress  71.40
606  2023-08   stress  74.00
607  2023-09   stress  91.25
608  2023-10   stress  92.00
609  2023-11   stress  98.00

[610 rows x 3 columns]

In [9]:
melted_df.to_json('../home/trend_data.json', orient='records')

In [33]:
json_data = melted_df.to_dict(orient='records')

In [35]:
json_data.to_json('../home/trend_data.json', orient='records')

AttributeError: 'list' object has no attribute 'to_json'

In [7]:
df

   Month of Year         District   AQHI
0         201601  Central/Western  3.341
1         201601          Eastern  3.266
2         201601        Kwun Tong  3.446
3         201601     Sham Shui Po  3.425
4         201601       Kwai Chung  3.415

In [12]:
mhissue = pd.read_json('../mental_states/state_prevalence.json')

In [13]:
mhissue

,state,depression,suicide,ptsd,psychosis,prevalence_percent
0,Wyoming,32.653597,15.376562,16.931495,31.789745,22.088968
1,Wisconsin,27.951589,15.315707,11.889602,31.920444,19.811067
2,West Virginia,32.866712,20.078981,18.396385,32.305847,23.961812
3,Washington,31.374811,16.255977,13.981691,35.199747,22.984040
4,Virginia,29.911109,14.243936,12.774416,32.769153,18.312507
5,Vermont,28.656846,16.729402,17.039206,32.374491,21.788564
6,Utah,38.256728,17.945012,14.469851,42.271137,25.734516
7,Texas,29.097864,13.685343,10.593356,31.742816,16.897685
8,Tennessee,32.328739,16.917034,14.637535,31.941654,18.891209
9,South Dakota,34.845696,16.641054,16.976108,37.414449,17.976502
10,South Carolina,28.454709,15.681878,12.098549,30.092251,18.937701
11,Rhode Island,23.639799,9.401156,8.397149,26.743093,21.741420
12,Pennsylvania,26.102942,13.768839,11.917567,28.702437,19.130215
13,Oregon,33.983686,19.523545,13.989127,37.657598,23.328170
14,Oklahoma,32.909927,20.067029,18.160661,33.787860,21.996867
15,Ohio,31.112009,16.714747,14.235973,34.660391,22.833347
16,North Dakota,30.711738,18.323810,14.968746,32.389270,20.034276
17,North Carolina,26.338331,13.391890,10.927706,28.802515,19.071458
18,New York,25.035399,10.596941,8.308163,28.438318,19.013670
19,New Mexico,25.899426,12.666143,11.531861,29.160485,21.123806
20,New Jersey,23.653494,9.593046,7.154319,27.171303,16.041147
21,New Hampshire,29.157835,15.334862,13.534995,29.157835,21.847494
22,Nevada,29.039523,14.249405,10.655247,33.619689,21.601010
23,Nebraska,32.031500,16.448608,13.494988,35.596214,19.830617
24,Montana,32.419578,17.024806,14.579754,34.411843,20.307657
25,Missouri,30.608670,17.395711,14.915242,31.824586,22.060314
26,Mississippi,29.220686,13.559483,17.051050,28.542712,19.409537
27,Minnesota,29.943634,14.227169,14.770324,34.481611,20.101685
28,Michigan,29.301118,15.172905,13.431752,31.629288,19.984479
29,Massachusetts,25.698943,10.938157,9.578046,29.177965,20.702715
30,Maryland,24.979202,11.711028,8.937364,29.942601,17.335813
31,Maine,31.043974,18.874153,16.177846,35.270618,21.600000
32,Louisiana,21.950469,11.872717,9.601979,23.485920,20.542690
33,Kentucky,33.197365,17.984678,17.452456,34.660977,21.870770
34,Kansas,32.508889,17.549348,15.368458,34.349015,20.161458
35,Iowa,32.257266,16.441811,16.097315,35.639582,18.330900
36,Indiana,35.380625,19.438773,17.513997,36.467903,21.744862
37,Illinois,26.721448,12.011236,10.393428,29.562476,18.808562
38,Idaho,38.455003,16.676109,12.625446,41.821789,21.944904
39,Hawaii,35.864099,12.000946,8.740574,41.344300,17.187801
40,Georgia,29.140060,14.796891,12.093079,32.334633,17.470522
41,Florida,25.393543,13.084722,9.604645,27.762566,16.916320
42,District of Columbia,27.759122,14.028804,11.491680,33.281098,22.157166
43,Delaware,34.184320,16.843003,15.946039,40.263747,20.449464
44,Connecticut,28.455759,13.257167,10.566905,31.950326,18.457439
45,Colorado,37.542569,18.650845,14.831207,41.224562,22.463040
46,California,27.843024,11.565368,9.503582,31.846812,19.100992
47,Arkansas,34.039561,20.258496,17.647695,34.270897,19.949957
48,Arizona,33.450994,15.997106,12.904882,37.161663,19.813094
49,Alaska,50.227045,25.659469,23.612171,56.368939,21.130817
50,Alabama,30.516618,17.421060,12.063786,32.480951,20.674820

In [14]:
mhissue.sort_values(by='depression', ascending=False)

,state,depression,suicide,ptsd,psychosis,prevalence_percent
49,Alaska,50.227045,25.659469,23.612171,56.368939,21.130817
38,Idaho,38.455003,16.676109,12.625446,41.821789,21.944904
6,Utah,38.256728,17.945012,14.469851,42.271137,25.734516
45,Colorado,37.542569,18.650845,14.831207,41.224562,22.463040
39,Hawaii,35.864099,12.000946,8.740574,41.344300,17.187801
36,Indiana,35.380625,19.438773,17.513997,36.467903,21.744862
9,South Dakota,34.845696,16.641054,16.976108,37.414449,17.976502
43,Delaware,34.184320,16.843003,15.946039,40.263747,20.449464
47,Arkansas,34.039561,20.258496,17.647695,34.270897,19.949957
13,Oregon,33.983686,19.523545,13.989127,37.657598,23.328170
48,Arizona,33.450994,15.997106,12.904882,37.161663,19.813094
33,Kentucky,33.197365,17.984678,17.452456,34.660977,21.870770
14,Oklahoma,32.909927,20.067029,18.160661,33.787860,21.996867
2,West Virginia,32.866712,20.078981,18.396385,32.305847,23.961812
0,Wyoming,32.653597,15.376562,16.931495,31.789745,22.088968
34,Kansas,32.508889,17.549348,15.368458,34.349015,20.161458
24,Montana,32.419578,17.024806,14.579754,34.411843,20.307657
8,Tennessee,32.328739,16.917034,14.637535,31.941654,18.891209
35,Iowa,32.257266,16.441811,16.097315,35.639582,18.330900
23,Nebraska,32.031500,16.448608,13.494988,35.596214,19.830617
3,Washington,31.374811,16.255977,13.981691,35.199747,22.984040
15,Ohio,31.112009,16.714747,14.235973,34.660391,22.833347
31,Maine,31.043974,18.874153,16.177846,35.270618,21.600000
16,North Dakota,30.711738,18.323810,14.968746,32.389270,20.034276
25,Missouri,30.608670,17.395711,14.915242,31.824586,22.060314
50,Alabama,30.516618,17.421060,12.063786,32.480951,20.674820
27,Minnesota,29.943634,14.227169,14.770324,34.481611,20.101685
4,Virginia,29.911109,14.243936,12.774416,32.769153,18.312507
28,Michigan,29.301118,15.172905,13.431752,31.629288,19.984479
26,Mississippi,29.220686,13.559483,17.051050,28.542712,19.409537
21,New Hampshire,29.157835,15.334862,13.534995,29.157835,21.847494
40,Georgia,29.140060,14.796891,12.093079,32.334633,17.470522
7,Texas,29.097864,13.685343,10.593356,31.742816,16.897685
22,Nevada,29.039523,14.249405,10.655247,33.619689,21.601010
5,Vermont,28.656846,16.729402,17.039206,32.374491,21.788564
44,Connecticut,28.455759,13.257167,10.566905,31.950326,18.457439
10,South Carolina,28.454709,15.681878,12.098549,30.092251,18.937701
1,Wisconsin,27.951589,15.315707,11.889602,31.920444,19.811067
46,California,27.843024,11.565368,9.503582,31.846812,19.100992
42,District of Columbia,27.759122,14.028804,11.491680,33.281098,22.157166
37,Illinois,26.721448,12.011236,10.393428,29.562476,18.808562
17,North Carolina,26.338331,13.391890,10.927706,28.802515,19.071458
12,Pennsylvania,26.102942,13.768839,11.917567,28.702437,19.130215
19,New Mexico,25.899426,12.666143,11.531861,29.160485,21.123806
29,Massachusetts,25.698943,10.938157,9.578046,29.177965,20.702715
41,Florida,25.393543,13.084722,9.604645,27.762566,16.916320
18,New York,25.035399,10.596941,8.308163,28.438318,19.013670
30,Maryland,24.979202,11.711028,8.937364,29.942601,17.335813
20,New Jersey,23.653494,9.593046,7.154319,27.171303,16.041147
11,Rhode Island,23.639799,9.401156,8.397149,26.743093,21.741420
32,Louisiana,21.950469,11.872717,9.601979,23.485920,20.542690